/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  ahill
 * Created: Aug 10, 2017
 */

DELETE FROM public.owners WHERE 1=1;

INSERT INTO public.owners (id, owner) VALUES(1,'AcidStar');
INSERT INTO public.owners (id, owner) VALUES(2,'Angel_of_Music');
INSERT INTO public.owners (id, owner) VALUES(3,'Asperi');
INSERT INTO public.owners (id, owner) VALUES(4,'Balanora');
INSERT INTO public.owners (id, owner) VALUES(5,'Black Unicorn');
INSERT INTO public.owners (id, owner) VALUES(6,'BloodBlackRose65');
INSERT INTO public.owners (id, owner) VALUES(7,'Brookie Cookie22');
INSERT INTO public.owners (id, owner) VALUES(8,'Calomel');
INSERT INTO public.owners (id, owner) VALUES(9,'Celestial');
INSERT INTO public.owners (id, owner) VALUES(10,'CosmicDragon');
INSERT INTO public.owners (id, owner) VALUES(11,'Countryqt05');
INSERT INTO public.owners (id, owner) VALUES(12,'Curious Pikachu');
INSERT INTO public.owners (id, owner) VALUES(13,'Danza');
INSERT INTO public.owners (id, owner) VALUES(14,'Darkspark');
INSERT INTO public.owners (id, owner) VALUES(15,'Dawn Angel');
INSERT INTO public.owners (id, owner) VALUES(16,'DawnStar7');
INSERT INTO public.owners (id, owner) VALUES(17,'debijayn');
INSERT INTO public.owners (id, owner) VALUES(18,'Deirdre');
INSERT INTO public.owners (id, owner) VALUES(19,'Delicious');
INSERT INTO public.owners (id, owner) VALUES(20,'Demondreamer');
INSERT INTO public.owners (id, owner) VALUES(21,'DeVenn');
INSERT INTO public.owners (id, owner) VALUES(22,'Devlish Smooch');
INSERT INTO public.owners (id, owner) VALUES(23,'Dream of Glory');
INSERT INTO public.owners (id, owner) VALUES(24,'DreamDove');
INSERT INTO public.owners (id, owner) VALUES(25,'DreamerGirl');
INSERT INTO public.owners (id, owner) VALUES(26,'Ember');
INSERT INTO public.owners (id, owner) VALUES(27,'Emislove');
INSERT INTO public.owners (id, owner) VALUES(28,'Esperanza');
INSERT INTO public.owners (id, owner) VALUES(29,'Faith');
INSERT INTO public.owners (id, owner) VALUES(30,'Fallendustfloating');
INSERT INTO public.owners (id, owner) VALUES(31,'Fantasy_Rocks13');
INSERT INTO public.owners (id, owner) VALUES(32,'Flora');
INSERT INTO public.owners (id, owner) VALUES(33,'freakingenius');
INSERT INTO public.owners (id, owner) VALUES(34,'FreeStar');
INSERT INTO public.owners (id, owner) VALUES(35,'FROGS');
INSERT INTO public.owners (id, owner) VALUES(36,'Fuzzly');
INSERT INTO public.owners (id, owner) VALUES(37,'Gabaldon');
INSERT INTO public.owners (id, owner) VALUES(38,'Garney');
INSERT INTO public.owners (id, owner) VALUES(39,'geob');
INSERT INTO public.owners (id, owner) VALUES(40,'Gethsemane');
INSERT INTO public.owners (id, owner) VALUES(41,'Greywolf');
INSERT INTO public.owners (id, owner) VALUES(42,'Harvest Moon');
INSERT INTO public.owners (id, owner) VALUES(43,'HayHay');
INSERT INTO public.owners (id, owner) VALUES(44,'Hera');
INSERT INTO public.owners (id, owner) VALUES(45,'Holiday');
INSERT INTO public.owners (id, owner) VALUES(46,'Hollywood');
INSERT INTO public.owners (id, owner) VALUES(47,'i luv horses');
INSERT INTO public.owners (id, owner) VALUES(48,'icklep');
INSERT INTO public.owners (id, owner) VALUES(49,'jadecorrine');
INSERT INTO public.owners (id, owner) VALUES(50,'Jellythunda');
INSERT INTO public.owners (id, owner) VALUES(51,'jward72182');
INSERT INTO public.owners (id, owner) VALUES(52,'kaats711');
INSERT INTO public.owners (id, owner) VALUES(53,'Kalioepe');
INSERT INTO public.owners (id, owner) VALUES(54,'kaoskat');
INSERT INTO public.owners (id, owner) VALUES(55,'Khalira');
INSERT INTO public.owners (id, owner) VALUES(56,'KrystaLake');
INSERT INTO public.owners (id, owner) VALUES(57,'Lady Everlasting');
INSERT INTO public.owners (id, owner) VALUES(58,'Lady Jade');
INSERT INTO public.owners (id, owner) VALUES(59,'Lady Whimsy');
INSERT INTO public.owners (id, owner) VALUES(60,'Leafy');
INSERT INTO public.owners (id, owner) VALUES(61,'Lectral');
INSERT INTO public.owners (id, owner) VALUES(62,'Leopardstar');
INSERT INTO public.owners (id, owner) VALUES(63,'Liria');
INSERT INTO public.owners (id, owner) VALUES(64,'Lokitha');
INSERT INTO public.owners (id, owner) VALUES(65,'LostDollie');
INSERT INTO public.owners (id, owner) VALUES(66,'Luner Wolf');
INSERT INTO public.owners (id, owner) VALUES(67,'LvSoulFriend');
INSERT INTO public.owners (id, owner) VALUES(68,'Magic Paintbrush');
INSERT INTO public.owners (id, owner) VALUES(69,'Math');
INSERT INTO public.owners (id, owner) VALUES(70,'mblansett');
INSERT INTO public.owners (id, owner) VALUES(71,'Melissa_13');
INSERT INTO public.owners (id, owner) VALUES(72,'MidnightPhantom');
INSERT INTO public.owners (id, owner) VALUES(73,'moonlily');
INSERT INTO public.owners (id, owner) VALUES(74,'Moonlit_Arcane');
INSERT INTO public.owners (id, owner) VALUES(75,'NekoFei-Tan');
INSERT INTO public.owners (id, owner) VALUES(76,'Nephthys');
INSERT INTO public.owners (id, owner) VALUES(77,'Niahm');
INSERT INTO public.owners (id, owner) VALUES(78,'Nighthenge2');
INSERT INTO public.owners (id, owner) VALUES(79,'Nightpaw');
INSERT INTO public.owners (id, owner) VALUES(80,'PandaBear');
INSERT INTO public.owners (id, owner) VALUES(81,'patch255');
INSERT INTO public.owners (id, owner) VALUES(82,'perryunicornboy');
INSERT INTO public.owners (id, owner) VALUES(83,'Pikachu');
INSERT INTO public.owners (id, owner) VALUES(84,'Pinkmoonbeam');
INSERT INTO public.owners (id, owner) VALUES(85,'Pnwy');
INSERT INTO public.owners (id, owner) VALUES(86,'PoisonedPromise');
INSERT INTO public.owners (id, owner) VALUES(87,'Poupou');
INSERT INTO public.owners (id, owner) VALUES(88,'Pristine');
INSERT INTO public.owners (id, owner) VALUES(89,'RainbowbriteQuesters');
INSERT INTO public.owners (id, owner) VALUES(90,'red_uni387');
INSERT INTO public.owners (id, owner) VALUES(91,'Rhaevin');
INSERT INTO public.owners (id, owner) VALUES(92,'runewarden');
INSERT INTO public.owners (id, owner) VALUES(93,'sam6284');
INSERT INTO public.owners (id, owner) VALUES(94,'Scullisto');
INSERT INTO public.owners (id, owner) VALUES(95,'Shades of Venus');
INSERT INTO public.owners (id, owner) VALUES(96,'Shadow Falls');
INSERT INTO public.owners (id, owner) VALUES(97,'Shadowphyr');
INSERT INTO public.owners (id, owner) VALUES(98,'shazza_dee86');
INSERT INTO public.owners (id, owner) VALUES(99,'Silent-Moon');
INSERT INTO public.owners (id, owner) VALUES(100,'Silverfoxkit');
INSERT INTO public.owners (id, owner) VALUES(101,'Song of Artemis');
INSERT INTO public.owners (id, owner) VALUES(102,'SplitX');
INSERT INTO public.owners (id, owner) VALUES(103,'springacres');
INSERT INTO public.owners (id, owner) VALUES(104,'star_gazer');
INSERT INTO public.owners (id, owner) VALUES(105,'Summerlove');
INSERT INTO public.owners (id, owner) VALUES(106,'Sunchaser109');
INSERT INTO public.owners (id, owner) VALUES(107,'Sushidragon');
INSERT INTO public.owners (id, owner) VALUES(108,'Suta8889');
INSERT INTO public.owners (id, owner) VALUES(109,'Sweet Intoxikation');
INSERT INTO public.owners (id, owner) VALUES(110,'Takaeji');
INSERT INTO public.owners (id, owner) VALUES(111,'Taruia');
INSERT INTO public.owners (id, owner) VALUES(112,'tbiris');
INSERT INTO public.owners (id, owner) VALUES(113,'The Black Unicorn');
INSERT INTO public.owners (id, owner) VALUES(114,'The Fox');
INSERT INTO public.owners (id, owner) VALUES(115,'Thera');
INSERT INTO public.owners (id, owner) VALUES(116,'tiirikka');
INSERT INTO public.owners (id, owner) VALUES(117,'Timeless Dreamer');
INSERT INTO public.owners (id, owner) VALUES(118,'Touzoku');
INSERT INTO public.owners (id, owner) VALUES(119,'tsukiclowes');
INSERT INTO public.owners (id, owner) VALUES(120,'TwilightPanther');
INSERT INTO public.owners (id, owner) VALUES(121,'TygerNight');
INSERT INTO public.owners (id, owner) VALUES(122,'Ulliea12');
INSERT INTO public.owners (id, owner) VALUES(123,'usedog2');
INSERT INTO public.owners (id, owner) VALUES(124,'Varuna');
INSERT INTO public.owners (id, owner) VALUES(125,'waswhatever');
INSERT INTO public.owners (id, owner) VALUES(126,'whitewolf');
INSERT INTO public.owners (id, owner) VALUES(127,'willowbean');
INSERT INTO public.owners (id, owner) VALUES(128,'WillowDragon');
INSERT INTO public.owners (id, owner) VALUES(129,'Wolfstorm');
INSERT INTO public.owners (id, owner) VALUES(130,'x Sunneh x');
INSERT INTO public.owners (id, owner) VALUES(131,'xJenniferx');
INSERT INTO public.owners (id, owner) VALUES(132,'xLostDestinyx');
INSERT INTO public.owners (id, owner) VALUES(133,'Zephyr');
INSERT INTO public.owners (id, owner) VALUES(134,'Zhuria');
INSERT INTO public.owners (id, owner) VALUES(135,'Zynax');

SELECT * FROM public.owners;