DELETE FROM public."tags" WHERE 1=1;
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(101 , 'With Foal' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(102 , 'Weanling' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(103 , 'Everfoal' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(104 , 'Koré' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(105 , 'Koros' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(106 , 'Mare' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(107 , 'Stallion' , 'Descriptor' , 1);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(108 , 'Foundation' , 'Descriptor' , 1);

INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(201 , 'Unikoré' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(202 , 'Mesopippen' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(203 , 'Nordenhjørn' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(204 , 'Aviquinn' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(205 , 'Torègarde' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(206 , 'Tang' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(207 , '(Tank)' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(208 , 'Alicorn' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(209 , 'Avipippen' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(210 , 'Avinorden' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(211 , 'Mesotore' , 'Breed' , 2);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(212 , 'Hybrid' , 'Breed' , 2);


INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(301 , 'Black' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(302 , 'Chestnut' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(303 , 'Bay' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(304 , 'Cream' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(305 , 'Double Cream' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(306 , 'Dun' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(307 , 'Silver' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(308 , 'Sabino' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(309 , 'Tobiano' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(310 , 'Sikelia' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(311 , 'Splash' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(312 , 'Overo' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(313 , 'Roan ' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(314 , 'Rabicano' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(315 , 'Appaloosa' , 'Genetics' , 3);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(316 , 'Grey' , 'Genetics' , 3);


INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(401 , 'Liver' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(402 , 'Sorrel' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(403 , 'Flaxen' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(404 , 'Sooty' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(405 , 'Wild Bay' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(406 , 'Seal Bay' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(407 , 'Palomino' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(408 , 'Buckskin' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(409 , 'Cremello' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(410 , 'Perlino' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(411 , 'Smokey Black' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(412 , 'Smokey Cream' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(413 , 'Grullo' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(414 , 'Classic Dun' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(415 , 'Red Dun' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(416 , 'Dunskin' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(417 , 'Dunalino' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(418 , 'Silver Dapple' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(419 , 'Silver Bay' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(420 , 'Silver Dun' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(421 , 'Silver Grullo' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(422 , 'Blanket Appaloosa' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(423 , 'Leopard ' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(424 , 'Varnish' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(425 , 'Snowflake' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(426 , 'Frost' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(427 , 'Few Spot' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(428 , 'Pintaloosa' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(429 , 'Dapple Grey' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(430 , 'Rose Grey' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(431 , 'Steel Grey' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(432 , 'Mulberry Grey' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(433 , 'Fleabitten ' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(434 , 'Champagne' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(435 , 'Wedgwood ' , 'Color' , 4);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(436 , 'Fantasy' , 'Color' , 4);


INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(501 , 'Winter Celebration' , 'Event' , 5);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(502 , 'Birthday Bash' , 'Event' , 5);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(503 , 'Harvest Festival' , 'Event' , 5);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(504 , 'Winter Solstice' , 'Event' , 5);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(505 , 'RP Quest' , 'Event' , 5);


INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(601 , 'Imperial Blue' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(602 , 'Pale Amber' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(603 , 'Rose Blush' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(604 , 'Countershade' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(605 , 'Starburst' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(606 , 'Mottle' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(607 , 'Brindle' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(608 , 'Moonstone' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(609 , 'Celestial' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(610 , 'Aurora ' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(611 , 'Jade' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(612 , 'Gypsy' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(613 , 'Silverfade' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(614 , 'Sikelia' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(615 , 'Passion’s Flame' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(616 , 'Twinning ' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(617 , 'Sunstone' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(618 , 'Pebble of Youth' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(619 , 'Probability ' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(620 , 'Kal’s Blessing' , 'Stone' , 6);
INSERT INTO public.tags (id, tagname, typename, typeid) VALUES(621 , 'Kaedon’s Consent' , 'Stone' , 6);

SELECT * FROM public."tags";